import type { NoteCode } from "@fetha/engine";

const en = {
  create: {
    overline: "New backtest",
    title: "Run a backtest",
    universe: "Universe",
    universeHint: "Only instruments already on your watchlist.",
    period: "Period",
    from: "From",
    to: "To",
    capital: "Initial capital",
    limits: "Risk limits",
    limitsEnforce: "Enforce",
    limitsWarn: "Warn only",
    submit: "Run backtest",
    error: "Couldn't create the run. Check the fields and try again.",
    empty: "Add at least one instrument to your watchlist to run a backtest.",
  },
  report: {
    overline: "Backtest",
    pending: "Not run yet.",
    run: "Run",
    running: "Running…",
    paused: "Paused at session {sessionsDone} of {sessionsTotal}. Continue to keep going.",
    resume: "Continue",
    failed: "The run failed: {error}",
    metrics: {
      sessions: "Sessions",
      operations: "Operations",
      totalReturn: "Total return",
      cagr: "CAGR",
      maxDrawdown: "Max drawdown",
      sharpe: "Sharpe",
      winRate: "Win rate",
      profitFactor: "Profit factor",
      exposure: "Exposure",
      fees: "Fees",
      taxes: "Taxes",
      slippage: "Slippage",
    },
    equityCurve: "Equity curve",
    drawdown: "Drawdown",
    distribution: "Distribution of returns",
    operationsTable: {
      title: "Operations",
      columns: { underlying: "Instrument", openedAt: "Opened", closedAt: "Closed", pnl: "P&L" },
      empty: "No operations in this period.",
    },
    missedEntries: {
      title: "Missed entries",
      columns: { ticker: "Instrument", signalAt: "Signal", reason: "Reason" },
      empty: "No missed entries.",
    },
    limitBreaches: {
      title: "Limit breaches",
      columns: { session: "Session", ticker: "Instrument", limit: "Limit" },
      empty: "No limit breaches.",
    },
    notes: "Notes",
  },
  notes: {
    european_pricing: "Priced as a European option; early exercise is not modeled.",
    dividend_yield_defaulted: "Dividend yield not given; assumed zero.",
    no_market_price: "No market price visible for this leg.",
    iv_from_average_price: "Implied volatility computed from the day's average price.",
    iv_not_converged: "The implied-volatility calculation did not converge.",
    below_intrinsic: "Price below intrinsic value.",
    stale_price: "Price carried forward from the series' last trade.",
    no_risk_profile: "No risk profile; limits were not applied.",
    limit_breach_warned: "Limit breach recorded as a warning only.",
    missed_entry: "Entry not filled: no trade in the following session.",
    intraday_option_fill_at_fair_value: "Intraday fill at fair value, not a traded price.",
    short_window_not_annualized: "Window too short to annualize this metric.",
    non_positive_equity: "Equity was non-positive at some point in the run.",
    no_thesis_claim: "No thesis recorded for this decision.",
    no_operation: "No operation was opened.",
    unbounded_max_loss: "Max loss is unbounded.",
    zero_max_loss: "Max loss computed as zero.",
    iv_index_not_bracketed: "No pair of expiries brackets 30 calendar days ahead.",
    risk_free_rate_defaulted: "Risk-free rate not given; assumed zero.",
    negative_cash: "Cash went negative at some point in the run.",
    settlement_pending: "Settlement still pending at period end.",
    settlement_costs_not_modeled: "Settlement costs are not modeled.",
    less_than_one_effective_unit: "Sizing resulted in less than one effective unit.",
    stale_price_across_corporate_action: "Price carried forward across a corporate action.",
    option_strike_unadjusted_across_corporate_action:
      "The option's strike was not adjusted for a corporate action.",
  } satisfies Record<NoteCode, string>,
};

const ptBR = {
  create: {
    overline: "Nova simulação",
    title: "Rodar um backtest",
    universe: "Universo",
    universeHint: "Só ativos que já estão na sua watchlist.",
    period: "Período",
    from: "De",
    to: "Até",
    capital: "Capital inicial",
    limits: "Limites de risco",
    limitsEnforce: "Aplicar",
    limitsWarn: "Só avisar",
    submit: "Rodar backtest",
    error: "Não foi possível criar a simulação. Confira os campos e tente novamente.",
    empty: "Adicione ao menos um ativo à sua watchlist para rodar um backtest.",
  },
  report: {
    overline: "Backtest",
    pending: "Ainda não foi executado.",
    run: "Executar",
    running: "Executando…",
    paused: "Pausado no pregão {sessionsDone} de {sessionsTotal}. Continue para prosseguir.",
    resume: "Continuar",
    failed: "A simulação falhou: {error}",
    metrics: {
      sessions: "Pregões",
      operations: "Operações",
      totalReturn: "Retorno total",
      cagr: "CAGR",
      maxDrawdown: "Drawdown máximo",
      sharpe: "Sharpe",
      winRate: "Taxa de acerto",
      profitFactor: "Fator de lucro",
      exposure: "Exposição",
      fees: "Taxas B3",
      taxes: "Impostos",
      slippage: "Deslizamento",
    },
    equityCurve: "Curva de patrimônio",
    drawdown: "Drawdown",
    distribution: "Distribuição de retornos",
    operationsTable: {
      title: "Operações",
      columns: { underlying: "Ativo", openedAt: "Aberta em", closedAt: "Fechada em", pnl: "P&L" },
      empty: "Nenhuma operação nesse período.",
    },
    missedEntries: {
      title: "Entradas perdidas",
      columns: { ticker: "Ativo", signalAt: "Sinal", reason: "Motivo" },
      empty: "Nenhuma entrada perdida.",
    },
    limitBreaches: {
      title: "Estouros de limite",
      columns: { session: "Pregão", ticker: "Ativo", limit: "Limite" },
      empty: "Nenhum estouro de limite.",
    },
    notes: "Notas",
  },
  // Every engine NoteCode (ADR-0013), translated once here so a report never
  // shows the engine's own English developer-facing message
  // (DESIGN.md "Approximation notes").
  notes: {
    european_pricing: "Precificado como opção europeia; o exercício antecipado não é modelado.",
    dividend_yield_defaulted: "Dividend yield não informado; assumido zero.",
    no_market_price: "Sem preço de mercado visível para esta perna.",
    iv_from_average_price: "Volatilidade implícita calculada a partir do preço médio do dia.",
    iv_not_converged: "O cálculo da volatilidade implícita não convergiu.",
    below_intrinsic: "Preço abaixo do valor intrínseco.",
    stale_price: "Preço carregado do último negócio da série.",
    no_risk_profile: "Sem perfil de risco; os limites não foram aplicados.",
    limit_breach_warned: "Estouro de limite registrado apenas como aviso.",
    missed_entry: "Entrada não executada: sem negócio na sessão seguinte.",
    intraday_option_fill_at_fair_value:
      "Execução intradiária a valor justo, não a preço negociado.",
    short_window_not_annualized: "Janela curta demais para anualizar a métrica.",
    non_positive_equity: "Patrimônio não positivo em algum ponto da simulação.",
    no_thesis_claim: "Sem tese registrada para esta decisão.",
    no_operation: "Nenhuma operação foi aberta.",
    unbounded_max_loss: "Perda máxima não é limitada.",
    zero_max_loss: "Perda máxima calculada como zero.",
    iv_index_not_bracketed: "Nenhum par de vencimentos cobre os 30 dias corridos.",
    risk_free_rate_defaulted: "Taxa livre de risco não informada; assumida como zero.",
    negative_cash: "Caixa ficou negativo em algum ponto da simulação.",
    settlement_pending: "Liquidação ainda pendente no fim do período.",
    settlement_costs_not_modeled: "Custos de liquidação não modelados.",
    less_than_one_effective_unit: "Dimensionamento resultou em menos de uma unidade.",
    stale_price_across_corporate_action: "Preço carregado através de um evento societário.",
    option_strike_unadjusted_across_corporate_action:
      "Strike da opção não foi ajustado por um evento societário.",
  } satisfies Record<NoteCode, string>,
} satisfies typeof en;

export const backtestsStrings = { en, ptBR } as const;

export const t = backtestsStrings.ptBR;

export function noteMessage(code: NoteCode): string {
  return t.notes[code];
}
