const en = {
  chip: { noRiskProfile: "no risk profile" },
  builder: {
    overline: "New operation",
    title: "Operation builder",
    structure: "Structure",
    underlying: "Underlying",
    underlyingPlaceholder: "e.g. PETR4",
    price: "Price",
    pricing: "Pricing…",
    priceError: "Could not price this operation with the current data.",
    save: "Save operation",
    saved: "Operation saved.",
    saveError: "Could not save this operation.",
    notes: {
      no_market_price: "No market price for one or more legs; using the fair value estimate.",
      risk_free_rate_defaulted: "No CDI rate found; a default risk-free rate was used.",
      dividend_yield_defaulted: "No dividend yield found; assuming zero.",
      iv_not_converged: "Implied volatility did not converge for one or more legs.",
      stale_price: "The market price used is from a previous session.",
    },
    legsTable: {
      title: "Legs",
      side: "Side",
      quantity: "Quantity",
      instrument: "Instrument",
      type: "Type",
      strike: "Strike",
      expiry: "Expiry",
      price: "Price",
      delta: "Delta",
      iv: "IV",
      buy: "Buy",
      sell: "Sell",
      call: "Call",
      put: "Put",
      stock: "Stock",
      pickInstrument: "Pick an instrument",
      stale: "stale",
      noTrades: "no trades",
    },
    statBlocks: {
      title: "Result",
      netPremium: "Net premium",
      maxLoss: "Max loss",
      maxGain: "Max gain",
      breakEvens: "Break-evens",
      unbounded: "Unbounded",
    },
    greeksPanel: {
      title: "Greeks",
      delta: "Delta",
      gamma: "Gamma",
      theta: "Theta",
      vega: "Vega",
      thetaUnit: "/ session",
      vegaUnit: "/ point",
    },
    riskNotice: {
      title: "Limit breach",
      recordAnyway: "Record anyway",
      limits: {
        maxLossPerOperation: "Max loss per operation",
        maxExposurePerOperation: "Max exposure per operation",
        maxOpenOperations: "Max open operations",
        maxPremiumBought: "Max option premium bought",
      },
    },
    payoffChart: { underlying: "Underlying price", pnl: "P&L at expiry" },
  },
  list: {
    title: "Contemplated operations",
    newOperation: "New operation",
    empty: "No contemplated operations yet.",
    columns: {
      underlying: "Underlying",
      date: "Date",
      netPremium: "Net premium",
      maxLoss: "Max loss",
      breach: "Breach",
    },
  },
  riskProfileForm: {
    overline: "Risk profile",
    title: "Declared capital and limits",
    subtitle: "Fetha never reads your balance from a bank or broker; you declare it here.",
    declaredCapital: "Declared capital",
    maxLossPerOperation: "Max loss per operation",
    maxExposurePerOperation: "Max exposure per operation",
    maxOpenOperations: "Max open operations",
    maxPremiumBought: "Max option premium bought",
    asPercentOfCapital: "% of declared capital",
    submit: "Save risk profile",
    saved: "Risk profile saved.",
    errors: {
      invalid: "Check the values: capital must be positive and limits between 0 and 100%.",
    },
  },
};

const ptBR = {
  chip: { noRiskProfile: "sem perfil de risco" },
  builder: {
    overline: "Nova operação",
    title: "Montador de operações",
    structure: "Estrutura",
    underlying: "Ativo-objeto",
    underlyingPlaceholder: "ex.: PETR4",
    price: "Precificar",
    pricing: "Precificando…",
    priceError: "Não foi possível precificar esta operação com os dados atuais.",
    save: "Salvar operação",
    saved: "Operação salva.",
    saveError: "Não foi possível salvar esta operação.",
    notes: {
      no_market_price:
        "Faltou preço de mercado para uma ou mais pernas; usando a estimativa de valor justo.",
      risk_free_rate_defaulted: "CDI não encontrado; foi usada uma taxa livre de risco padrão.",
      dividend_yield_defaulted: "Dividend yield não encontrado; assumindo zero.",
      iv_not_converged: "A volatilidade implícita não convergiu para uma ou mais pernas.",
      stale_price: "O preço de mercado usado é de uma sessão anterior.",
    },
    legsTable: {
      title: "Pernas",
      side: "Lado",
      quantity: "Quantidade",
      instrument: "Instrumento",
      type: "Tipo",
      strike: "Strike",
      expiry: "Vencimento",
      price: "Preço",
      delta: "Delta",
      iv: "Vol. implícita",
      buy: "Compra",
      sell: "Venda",
      call: "Call",
      put: "Put",
      stock: "Ação",
      pickInstrument: "Escolha um instrumento",
      stale: "atrasado",
      noTrades: "sem negócios",
    },
    statBlocks: {
      title: "Resultado",
      netPremium: "Prêmio líquido",
      maxLoss: "Perda máxima",
      maxGain: "Ganho máximo",
      breakEvens: "Pontos de equilíbrio",
      unbounded: "Ilimitado",
    },
    greeksPanel: {
      title: "Gregas",
      delta: "Delta",
      gamma: "Gama",
      theta: "Theta",
      vega: "Vega",
      thetaUnit: "/ sessão",
      vegaUnit: "/ ponto",
    },
    riskNotice: {
      title: "Limite excedido",
      recordAnyway: "Registrar mesmo assim",
      limits: {
        maxLossPerOperation: "Perda máxima por operação",
        maxExposurePerOperation: "Exposição máxima por operação",
        maxOpenOperations: "Máximo de operações abertas",
        maxPremiumBought: "Prêmio máximo comprado em opções",
      },
    },
    payoffChart: { underlying: "Preço do ativo-objeto", pnl: "Resultado no vencimento" },
  },
  list: {
    title: "Operações contempladas",
    newOperation: "Nova operação",
    empty: "Nenhuma operação contemplada ainda.",
    columns: {
      underlying: "Ativo-objeto",
      date: "Data",
      netPremium: "Prêmio líquido",
      maxLoss: "Perda máxima",
      breach: "Limite",
    },
  },
  riskProfileForm: {
    overline: "Perfil de risco",
    title: "Capital declarado e limites",
    subtitle: "A Fetha nunca lê seu saldo de um banco ou corretora; você declara aqui.",
    declaredCapital: "Capital declarado",
    maxLossPerOperation: "Perda máxima por operação",
    maxExposurePerOperation: "Exposição máxima por operação",
    maxOpenOperations: "Máximo de operações abertas",
    maxPremiumBought: "Prêmio máximo comprado em opções",
    asPercentOfCapital: "% do capital declarado",
    submit: "Salvar perfil de risco",
    saved: "Perfil de risco salvo.",
    errors: {
      invalid: "Confira os valores: o capital deve ser positivo e os limites entre 0 e 100%.",
    },
  },
} satisfies typeof en;

export const portfolioStrings = { en, ptBR } as const;

export const t = portfolioStrings.ptBR;
