const en = {
  chip: { noRiskProfile: "no risk profile" },
  builder: {
    overline: "New operation",
    title: "Operation builder",
    structure: "Structure",
    underlying: "Underlying",
    underlyingPlaceholder: "e.g. PETR4",
    price: "Price",
    pricing: "Pricing…",
    priceError: "Could not price this operation with the current data.",
    save: "Save operation",
    saved: "Operation saved.",
    saveError: "Could not save this operation.",
    saveErrorNoMarketPrice:
      "One or more legs no longer have a market price; re-price before saving again.",
    notes: {
      no_market_price: "No market price for one or more legs; using the fair value estimate.",
      risk_free_rate_defaulted: "No CDI rate found; a default risk-free rate was used.",
      dividend_yield_defaulted: "No dividend yield found; assuming zero.",
      iv_not_converged: "Implied volatility did not converge for one or more legs.",
      stale_price: "The market price used is from a previous session.",
    },
    legsTable: {
      title: "Legs",
      side: "Side",
      quantity: "Quantity",
      instrument: "Instrument",
      type: "Type",
      strike: "Strike",
      expiry: "Expiry",
      price: "Price",
      delta: "Delta",
      iv: "IV",
      buy: "Buy",
      sell: "Sell",
      call: "Call",
      put: "Put",
      stock: "Stock",
      pickInstrument: "Pick an instrument",
      stale: "stale",
      noTrades: "no trades",
    },
    statBlocks: {
      title: "Result",
      netPremium: "Net premium",
      maxLoss: "Max loss",
      maxGain: "Max gain",
      breakEvens: "Break-evens",
      unbounded: "Unbounded",
    },
    greeksPanel: {
      title: "Greeks",
      delta: "Delta",
      gamma: "Gamma",
      theta: "Theta",
      vega: "Vega",
      thetaUnit: "/ session",
      vegaUnit: "/ point",
    },
    riskNotice: {
      title: "Limit breach",
      recordAnyway: "Record anyway",
      limits: {
        maxLossPerOperation: "Max loss per operation",
        maxExposurePerOperation: "Max exposure per operation",
        maxOpenOperations: "Max open operations",
        maxPremiumBought: "Max option premium bought",
      },
    },
    payoffChart: { underlying: "Underlying price", pnl: "P&L at expiry" },
  },
  dashboard: {
    title: "Positions and operations",
    markedAt: "marked at",
    importSpreadsheet: "Import B3 spreadsheet",
    recordFill: "Record fill",
    stats: {
      equity: "Equity",
      cash: "Cash",
      cashSub: "declared capital plus fills",
      unrealizedPnl: "Unrealized P&L",
      delta: "Delta",
      theta: "Theta",
      vega: "Vega",
    },
    valuationError: "Could not mark the portfolio with the current data.",
    positions: {
      title: "Positions",
      empty: "Positions appear here once you record or import fills.",
      instrument: "Instrument",
      type: "Type",
      quantity: "Quantity",
      averageCost: "Average cost",
      price: "Price",
      value: "Value",
      unrealizedPnl: "Unrealized P&L",
      stock: "Stock",
      call: "Call",
      put: "Put",
      option: "Option",
      fairValue: "fair value",
      noPrice: "no price",
      unknownSeries:
        "Series unknown to the reference data, not marked: group or settle it once the series is ingested.",
    },
    settlements: {
      title: "Pending settlement",
      subtitle: "Expired series; nothing settles until you confirm.",
      review: "Review settlement",
      expiredOn: "expired on",
      group: "Create operation",
      ungroupedHint: "Held outside any operation; create one to settle it.",
      proposalError: "No settlement proposal: the expiry session's data is missing.",
      dialogTitle: "Settlement of",
      underlyingClose: "Underlying close at expiry",
      leg: "Leg",
      strike: "Strike",
      intrinsic: "Intrinsic",
      outcome: "Outcome",
      stockPrice: "Stock fill price",
      costs: "Costs",
      confirm: "Confirm settlement",
      outcomes: {
        exercised: "Exercised",
        assigned: "Assigned",
        expired_worthless: "Expired worthless",
        kept: "Kept",
      },
    },
    operations: {
      title: "Operations",
      empty: "Group fills into an operation to track it as one structure.",
      underlying: "Underlying",
      status: "Status",
      expiry: "Expiry",
      legs: "Open legs",
      unrealizedPnl: "Unrealized P&L",
      opened: "Opened",
      statuses: { open: "open", closed: "closed", expired: "expired" },
      pendingSettlement: "settlement pending",
      ungroup: "Ungroup",
    },
    fills: {
      title: "Fills",
      empty: "No fills yet. Import the B3 spreadsheet or record one by hand.",
      date: "Date",
      side: "Side",
      instrument: "Instrument",
      quantity: "Quantity",
      price: "Price",
      costs: "Costs",
      source: "Source",
      operation: "Operation",
      buy: "Buy",
      sell: "Sell",
      sources: { manual: "manual", b3_import: "B3", settlement: "settlement" },
      select: "Select fill",
      groupNew: "Group into new operation",
      addTo: "Add to operation",
      pickOperation: "Pick an open operation",
      delete: "Delete",
      selected: "selected",
      unassigned: "—",
    },
    importDialog: {
      title: "Import B3 spreadsheet",
      description:
        "The Negotiation export (.xlsx) from B3's investor area. Re-importing the same file adds nothing twice.",
      file: "Spreadsheet",
      submit: "Import",
      result: (inserted: number, already: number) =>
        `${String(inserted)} fills imported, ${String(already)} already imported.`,
      skipped: (exercise: number, unsupported: number) =>
        `Skipped: ${String(exercise)} exercise rows (confirm them as settlements), ${String(unsupported)} rows from other markets.`,
    },
    recordDialog: {
      title: "Record fill",
      instrument: "Instrument",
      side: "Side",
      quantity: "Quantity",
      price: "Price",
      date: "Date",
      costs: "Costs (R$)",
      submit: "Record fill",
    },
    errors: {
      no_file: "Pick a spreadsheet to import.",
      too_large: "The file is larger than 1 MB; export a shorter period.",
      not_xlsx: "This file is not an .xlsx workbook.",
      missing_columns: "The spreadsheet does not have the Negotiation export's columns.",
      invalid_row: (row: number) => `Row ${String(row)} could not be read; nothing was imported.`,
      invalid_input: "Check the values and try again.",
      unknown_instrument: "Instrument not found in the reference data.",
      not_found: "It is no longer available; refresh the page.",
      conflict: "The operation changed since the proposal; review it again.",
      fills_unavailable: "One of these fills already belongs to an operation.",
      operation_unavailable: "That operation is no longer open.",
      unknown_series: "An option series is unknown to the reference data.",
      mixed_underlyings: "The selected fills span more than one underlying.",
      mixed_expiries: "The selected options have different expiries.",
      empty: "Pick at least one fill.",
      no_proposal: "There is no settlement to confirm for this operation.",
      invalid_choice: "Pick an allowed outcome for every leg.",
      rate_limited: "Too many changes in a short time. Try again in a moment.",
      not_a_session: "That date is not a trading session that has already opened.",
      unavailable: "Something went wrong; try again.",
    },
  },
  list: {
    title: "Contemplated operations",
    newOperation: "New operation",
    empty: "No contemplated operations yet.",
    columns: {
      underlying: "Underlying",
      date: "Date",
      netPremium: "Net premium",
      maxLoss: "Max loss",
      breach: "Breach",
    },
  },
  riskProfileForm: {
    overline: "Risk profile",
    title: "Declared capital and limits",
    subtitle: "Fetha never reads your balance from a bank or broker; you declare it here.",
    declaredCapital: "Declared capital",
    maxLossPerOperation: "Max loss per operation",
    maxExposurePerOperation: "Max exposure per operation",
    maxOpenOperations: "Max open operations",
    maxPremiumBought: "Max option premium bought",
    asPercentOfCapital: "% of declared capital",
    submit: "Save risk profile",
    saved: "Risk profile saved.",
    errors: {
      invalid: "Check the values: capital must be positive and limits between 0 and 100%.",
    },
  },
};

const ptBR = {
  chip: { noRiskProfile: "sem perfil de risco" },
  builder: {
    overline: "Nova operação",
    title: "Montador de operações",
    structure: "Estrutura",
    underlying: "Ativo-objeto",
    underlyingPlaceholder: "ex.: PETR4",
    price: "Precificar",
    pricing: "Precificando…",
    priceError: "Não foi possível precificar esta operação com os dados atuais.",
    save: "Salvar operação",
    saved: "Operação salva.",
    saveError: "Não foi possível salvar esta operação.",
    saveErrorNoMarketPrice:
      "Uma ou mais pernas perderam o preço de mercado; precifique novamente antes de salvar.",
    notes: {
      no_market_price:
        "Faltou preço de mercado para uma ou mais pernas; usando a estimativa de valor justo.",
      risk_free_rate_defaulted: "CDI não encontrado; foi usada uma taxa livre de risco padrão.",
      dividend_yield_defaulted: "Dividend yield não encontrado; assumindo zero.",
      iv_not_converged: "A volatilidade implícita não convergiu para uma ou mais pernas.",
      stale_price: "O preço de mercado usado é de uma sessão anterior.",
    },
    legsTable: {
      title: "Pernas",
      side: "Lado",
      quantity: "Quantidade",
      instrument: "Instrumento",
      type: "Tipo",
      strike: "Strike",
      expiry: "Vencimento",
      price: "Preço",
      delta: "Delta",
      iv: "Vol. implícita",
      buy: "Compra",
      sell: "Venda",
      call: "Call",
      put: "Put",
      stock: "Ação",
      pickInstrument: "Escolha um instrumento",
      stale: "atrasado",
      noTrades: "sem negócios",
    },
    statBlocks: {
      title: "Resultado",
      netPremium: "Prêmio líquido",
      maxLoss: "Perda máxima",
      maxGain: "Ganho máximo",
      breakEvens: "Pontos de equilíbrio",
      unbounded: "Ilimitado",
    },
    greeksPanel: {
      title: "Gregas",
      delta: "Delta",
      gamma: "Gama",
      theta: "Theta",
      vega: "Vega",
      thetaUnit: "/ sessão",
      vegaUnit: "/ ponto",
    },
    riskNotice: {
      title: "Limite excedido",
      recordAnyway: "Registrar mesmo assim",
      limits: {
        maxLossPerOperation: "Perda máxima por operação",
        maxExposurePerOperation: "Exposição máxima por operação",
        maxOpenOperations: "Máximo de operações abertas",
        maxPremiumBought: "Prêmio máximo comprado em opções",
      },
    },
    payoffChart: { underlying: "Preço do ativo-objeto", pnl: "Resultado no vencimento" },
  },
  dashboard: {
    title: "Posições e operações",
    markedAt: "marcada em",
    importSpreadsheet: "Importar planilha da B3",
    recordFill: "Registrar execução",
    stats: {
      equity: "Patrimônio",
      cash: "Caixa",
      cashSub: "capital declarado mais execuções",
      unrealizedPnl: "Resultado não realizado",
      delta: "Delta",
      theta: "Theta",
      vega: "Vega",
    },
    valuationError: "Não foi possível marcar a carteira com os dados atuais.",
    positions: {
      title: "Posições",
      empty: "As posições aparecem aqui depois que você registrar ou importar execuções.",
      instrument: "Ativo",
      type: "Tipo",
      quantity: "Quantidade",
      averageCost: "Custo médio",
      price: "Preço",
      value: "Valor",
      unrealizedPnl: "Resultado",
      stock: "Ação",
      call: "Call",
      put: "Put",
      option: "Opção",
      fairValue: "valor justo",
      noPrice: "sem preço",
      unknownSeries:
        "Série fora dos dados de referência, sem marcação: agrupe ou liquide depois que ela for ingerida.",
    },
    settlements: {
      title: "Liquidação pendente",
      subtitle: "Séries vencidas; nada é liquidado até você confirmar.",
      review: "Revisar liquidação",
      expiredOn: "venceu em",
      group: "Criar operação",
      ungroupedHint: "Fora de qualquer operação; crie uma para liquidar.",
      proposalError: "Sem proposta de liquidação: faltam os dados do pregão de vencimento.",
      dialogTitle: "Liquidação de",
      underlyingClose: "Fechamento do ativo-objeto no vencimento",
      leg: "Perna",
      strike: "Strike",
      intrinsic: "Intrínseco",
      outcome: "Resultado",
      stockPrice: "Preço da execução na ação",
      costs: "Custos",
      confirm: "Confirmar liquidação",
      outcomes: {
        exercised: "Exercida",
        assigned: "Exercício sofrido",
        expired_worthless: "Venceu sem valor",
        kept: "Mantida",
      },
    },
    operations: {
      title: "Operações",
      empty: "Agrupe execuções em uma operação para acompanhá-las como uma estrutura.",
      underlying: "Ativo-objeto",
      status: "Situação",
      expiry: "Vencimento",
      legs: "Pernas abertas",
      unrealizedPnl: "Resultado",
      opened: "Aberta em",
      statuses: { open: "aberta", closed: "encerrada", expired: "vencida" },
      pendingSettlement: "liquidação pendente",
      ungroup: "Desagrupar",
    },
    fills: {
      title: "Execuções",
      empty: "Nenhuma execução ainda. Importe a planilha da B3 ou registre uma à mão.",
      date: "Data",
      side: "Lado",
      instrument: "Ativo",
      quantity: "Quantidade",
      price: "Preço",
      costs: "Custos",
      source: "Origem",
      operation: "Operação",
      buy: "Compra",
      sell: "Venda",
      sources: { manual: "manual", b3_import: "B3", settlement: "liquidação" },
      select: "Selecionar execução",
      groupNew: "Agrupar em nova operação",
      addTo: "Adicionar à operação",
      pickOperation: "Escolha uma operação aberta",
      delete: "Excluir",
      selected: "selecionadas",
      unassigned: "—",
    },
    importDialog: {
      title: "Importar planilha da B3",
      description:
        "O extrato de Negociação (.xlsx) da Área do Investidor da B3. Importar o mesmo arquivo de novo não duplica nada.",
      file: "Planilha",
      submit: "Importar",
      result: (inserted: number, already: number) =>
        `${String(inserted)} execuções importadas, ${String(already)} já estavam na carteira.`,
      skipped: (exercise: number, unsupported: number) =>
        `Ignoradas: ${String(exercise)} linhas de exercício (confirme-as na liquidação pendente) e ${String(unsupported)} de outros mercados.`,
    },
    recordDialog: {
      title: "Registrar execução",
      instrument: "Ativo",
      side: "Lado",
      quantity: "Quantidade",
      price: "Preço",
      date: "Data",
      costs: "Custos (R$)",
      submit: "Registrar execução",
    },
    errors: {
      no_file: "Escolha uma planilha para importar.",
      too_large: "O arquivo passa de 1 MB; exporte um período menor.",
      not_xlsx: "Este arquivo não é uma planilha .xlsx.",
      missing_columns: "A planilha não tem as colunas do extrato de Negociação.",
      invalid_row: (row: number) =>
        `Não foi possível ler a linha ${String(row)}; nada foi importado.`,
      invalid_input: "Confira os valores e tente de novo.",
      unknown_instrument: "Ativo não encontrado nos dados de referência.",
      not_found: "Isto não está mais disponível; atualize a página.",
      conflict: "A operação mudou desde a proposta; revise de novo.",
      fills_unavailable: "Uma dessas execuções já pertence a uma operação.",
      operation_unavailable: "Essa operação não está mais aberta.",
      unknown_series: "Uma série de opção não está nos dados de referência.",
      mixed_underlyings: "As execuções selecionadas têm mais de um ativo-objeto.",
      mixed_expiries: "As opções selecionadas vencem em datas diferentes.",
      empty: "Escolha ao menos uma execução.",
      no_proposal: "Não há liquidação a confirmar nesta operação.",
      invalid_choice: "Escolha um resultado permitido para cada perna.",
      rate_limited: "Muitas alterações em pouco tempo. Tente de novo em instantes.",
      not_a_session: "Essa data não é um pregão que já abriu.",
      unavailable: "Algo deu errado; tente de novo.",
    },
  },
  list: {
    title: "Operações contempladas",
    newOperation: "Nova operação",
    empty: "Nenhuma operação contemplada ainda.",
    columns: {
      underlying: "Ativo-objeto",
      date: "Data",
      netPremium: "Prêmio líquido",
      maxLoss: "Perda máxima",
      breach: "Limite",
    },
  },
  riskProfileForm: {
    overline: "Perfil de risco",
    title: "Capital declarado e limites",
    subtitle: "A Fetha nunca lê seu saldo de um banco ou corretora; você declara aqui.",
    declaredCapital: "Capital declarado",
    maxLossPerOperation: "Perda máxima por operação",
    maxExposurePerOperation: "Exposição máxima por operação",
    maxOpenOperations: "Máximo de operações abertas",
    maxPremiumBought: "Prêmio máximo comprado em opções",
    asPercentOfCapital: "% do capital declarado",
    submit: "Salvar perfil de risco",
    saved: "Perfil de risco salvo.",
    errors: {
      invalid: "Confira os valores: o capital deve ser positivo e os limites entre 0 e 100%.",
    },
  },
} satisfies typeof en;

export const portfolioStrings = { en, ptBR } as const;

export const t = portfolioStrings.ptBR;
