const en = {
  shared: {
    signInWithPasswordLink: "Sign in with your password instead",
  },
  signUp: {
    title: "Create your account",
    subtitle: "Register to start studying and backtesting your own strategies.",
    nameLabel: "Name",
    emailLabel: "Email",
    passwordLabel: "Password",
    termsLabel: "I accept the terms of use",
    privacyLabel: "I accept the privacy policy",
    submit: "Register",
    alreadyHaveAccount: "Already registered?",
    signInLink: "Sign in",
  },
  signIn: {
    title: "Sign in",
    subtitle: "Enter your email and password to access your lab.",
    emailLabel: "Email",
    passwordLabel: "Password",
    submit: "Sign in",
    noAccount: "Not registered yet?",
    signUpLink: "Register",
    magicLinkLink: "Sign in with a magic link instead",
    forgotPasswordLink: "Forgot your password?",
  },
  verifyEmail: {
    title: "Confirm your registration",
    body: "We sent a confirmation link to {email}. Click the link to confirm your registration.",
    resend: "Resend email",
    resent: "We sent the email again.",
  },
  verificationResult: {
    successTitle: "Email confirmed",
    successBody: "Your email is confirmed. You can sign in now.",
    errorTitle: "We couldn't confirm your email",
    errorBody: "This confirmation link is invalid or has expired. Request a new one below.",
    signInLink: "Go to sign-in",
    resendLink: "Request a new confirmation link",
  },
  magicLink: {
    title: "Sign in with a magic link",
    subtitle: "Enter your email and we'll send you a link to sign in, no password needed.",
    emailLabel: "Email",
    submit: "Send magic link",
    sentTitle: "Check your email",
    sentBody: "We sent a magic link to {email}. Click the link to sign in.",
    sentBodyGeneric:
      "We sent a magic link to the email address you entered. Click the link to sign in.",
    errorTitle: "This magic link is invalid or has expired",
    errorBody: "Request a new magic link below.",
    requestAgainLink: "Request a new magic link",
  },
  passwordReset: {
    requestTitle: "Reset your password",
    requestSubtitle: "Enter your email and we'll send you a link to set a new password.",
    emailLabel: "Email",
    requestSubmit: "Send reset link",
    sentTitle: "Check your email",
    sentBody: "If {email} has an account, we sent a password reset link to that address.",
    sentBodyGeneric:
      "If the email address you entered has an account, we sent a password reset link to it.",
    confirmTitle: "Set a new password",
    newPasswordLabel: "New password",
    confirmSubmit: "Save new password",
    invalidLinkTitle: "This link is invalid or has expired",
    invalidLinkBody: "Request a new password reset link below.",
    requestAgainLink: "Request a new reset link",
  },
  terms: {
    title: "Terms of use",
    body: "Content in progress.",
  },
  privacy: {
    title: "Privacy policy",
    body: "Content in progress.",
  },
  errors: {
    invalidInput: "Check the fields highlighted below.",
    termsRequired: "You must accept the terms of use and the privacy policy.",
    registrationClosed: "Registration is closed at the moment.",
    signUpFailed: "We couldn't complete your registration. Try again.",
    invalidCredentials: "Incorrect email or password.",
    emailNotVerified: "Confirm your email before signing in.",
    rateLimited: "Too many attempts. Wait a moment and try again.",
    signInFailed: "We couldn't sign you in. Try again.",
    resendFailed: "We couldn't resend the email. Try again.",
    magicLinkFailed: "We couldn't send the magic link. Try again.",
    passwordResetRequestFailed: "We couldn't send the reset link. Try again.",
    passwordResetFailed: "We couldn't reset your password. Try again.",
    invalidResetToken: "This link is invalid or has expired.",
  },
  verificationEmail: {
    subject: "Confirm your email at Fetha",
    text: "Hello. Confirm your email to start using Fetha: {url}\n\nIf you didn't create this account, ignore this email.",
    html: '<p>Hello.</p><p>Confirm your email to start using Fetha:</p><p><a href="{url}">{url}</a></p><p>If you didn\'t create this account, ignore this email.</p>',
  },
  magicLinkEmail: {
    subject: "Your Fetha magic link",
    text: "Click the magic link below to sign in to Fetha: {url}\n\nThis link expires soon and can only be used once. If you didn't request it, ignore this email.",
    html: '<p>Click the magic link below to sign in to Fetha:</p><p><a href="{url}">{url}</a></p><p>This link expires soon and can only be used once. If you didn\'t request it, ignore this email.</p>',
  },
  passwordResetEmail: {
    subject: "Reset your Fetha password",
    text: "Click the link below to set a new password: {url}\n\nThis link expires soon and can only be used once. If you didn't request it, ignore this email.",
    html: '<p>Click the link below to set a new password:</p><p><a href="{url}">{url}</a></p><p>This link expires soon and can only be used once. If you didn\'t request it, ignore this email.</p>',
  },
  signOut: "Sign out",
};

const ptBR = {
  shared: {
    signInWithPasswordLink: "Entrar com sua senha",
  },
  signUp: {
    title: "Crie sua conta",
    subtitle: "Cadastre-se para estudar e testar suas próprias estratégias.",
    nameLabel: "Nome",
    emailLabel: "E-mail",
    passwordLabel: "Senha",
    termsLabel: "Aceito os termos de uso",
    privacyLabel: "Aceito a política de privacidade",
    submit: "Criar conta",
    alreadyHaveAccount: "Já tem conta?",
    signInLink: "Entrar",
  },
  signIn: {
    title: "Entrar",
    subtitle: "Informe seu e-mail e sua senha para acessar seu laboratório.",
    emailLabel: "E-mail",
    passwordLabel: "Senha",
    submit: "Entrar",
    noAccount: "Ainda não tem conta?",
    signUpLink: "Criar conta",
    magicLinkLink: "Entrar com link mágico",
    forgotPasswordLink: "Esqueceu sua senha?",
  },
  verifyEmail: {
    title: "Confirme seu cadastro",
    body: "Enviamos um link de confirmação para {email}. Clique no link para confirmar seu cadastro.",
    resend: "Reenviar e-mail",
    resent: "Enviamos o e-mail novamente.",
  },
  verificationResult: {
    successTitle: "E-mail confirmado",
    successBody: "Seu e-mail foi confirmado. Você já pode entrar.",
    errorTitle: "Não foi possível confirmar seu e-mail",
    errorBody: "Esse link de confirmação é inválido ou expirou. Peça um novo abaixo.",
    signInLink: "Ir para a tela de entrada",
    resendLink: "Pedir um novo link de confirmação",
  },
  magicLink: {
    title: "Entrar com link mágico",
    subtitle: "Informe seu e-mail e enviaremos um link para você entrar, sem precisar de senha.",
    emailLabel: "E-mail",
    submit: "Enviar link mágico",
    sentTitle: "Confira seu e-mail",
    sentBody: "Enviamos um link mágico para {email}. Clique no link para entrar.",
    sentBodyGeneric: "Enviamos um link mágico para o e-mail informado. Clique no link para entrar.",
    errorTitle: "Esse link mágico é inválido ou expirou",
    errorBody: "Peça um novo link mágico abaixo.",
    requestAgainLink: "Pedir um novo link mágico",
  },
  passwordReset: {
    requestTitle: "Redefinir sua senha",
    requestSubtitle: "Informe seu e-mail e enviaremos um link para você definir uma nova senha.",
    emailLabel: "E-mail",
    requestSubmit: "Enviar link de redefinição",
    sentTitle: "Confira seu e-mail",
    sentBody:
      "Se {email} tiver uma conta, enviamos um link de redefinição de senha para esse endereço.",
    sentBodyGeneric:
      "Se o e-mail informado tiver uma conta, enviamos um link de redefinição de senha para ele.",
    confirmTitle: "Defina uma nova senha",
    newPasswordLabel: "Nova senha",
    confirmSubmit: "Salvar nova senha",
    invalidLinkTitle: "Esse link é inválido ou expirou",
    invalidLinkBody: "Peça um novo link de redefinição abaixo.",
    requestAgainLink: "Pedir um novo link de redefinição",
  },
  terms: {
    title: "Termos de uso",
    body: "Conteúdo em elaboração.",
  },
  privacy: {
    title: "Política de privacidade",
    body: "Conteúdo em elaboração.",
  },
  errors: {
    invalidInput: "Confira os campos destacados abaixo.",
    termsRequired: "Você precisa aceitar os termos de uso e a política de privacidade.",
    registrationClosed: "O cadastro está fechado no momento.",
    signUpFailed: "Não foi possível concluir seu cadastro. Tente novamente.",
    invalidCredentials: "E-mail ou senha incorretos.",
    emailNotVerified: "Confirme seu e-mail antes de entrar.",
    rateLimited: "Muitas tentativas seguidas. Aguarde um instante e tente de novo.",
    signInFailed: "Não foi possível entrar. Tente novamente.",
    resendFailed: "Não foi possível reenviar o e-mail. Tente novamente.",
    magicLinkFailed: "Não foi possível enviar o link mágico. Tente novamente.",
    passwordResetRequestFailed: "Não foi possível enviar o link de redefinição. Tente novamente.",
    passwordResetFailed: "Não foi possível redefinir sua senha. Tente novamente.",
    invalidResetToken: "Esse link é inválido ou expirou.",
  },
  verificationEmail: {
    subject: "Confirme seu e-mail no Fetha",
    text: "Olá! Confirme seu e-mail para começar a usar o Fetha: {url}\n\nSe você não criou esta conta, ignore este e-mail.",
    html: '<p>Olá!</p><p>Confirme seu e-mail para começar a usar o Fetha:</p><p><a href="{url}">{url}</a></p><p>Se você não criou esta conta, ignore este e-mail.</p>',
  },
  magicLinkEmail: {
    subject: "Seu link mágico do Fetha",
    text: "Clique no link mágico abaixo para entrar no Fetha: {url}\n\nEsse link expira em pouco tempo e só pode ser usado uma vez. Se você não pediu este link, ignore este e-mail.",
    html: '<p>Clique no link mágico abaixo para entrar no Fetha:</p><p><a href="{url}">{url}</a></p><p>Esse link expira em pouco tempo e só pode ser usado uma vez. Se você não pediu este link, ignore este e-mail.</p>',
  },
  passwordResetEmail: {
    subject: "Redefina sua senha no Fetha",
    text: "Clique no link abaixo para definir uma nova senha: {url}\n\nEsse link expira em pouco tempo e só pode ser usado uma vez. Se você não pediu essa redefinição, ignore este e-mail.",
    html: '<p>Clique no link abaixo para definir uma nova senha:</p><p><a href="{url}">{url}</a></p><p>Esse link expira em pouco tempo e só pode ser usado uma vez. Se você não pediu essa redefinição, ignore este e-mail.</p>',
  },
  signOut: "Sair",
} satisfies typeof en;

export const authStrings = { en, ptBR } as const;

export const t = authStrings.ptBR;
