const en = {
  builder: {
    overline: "New operation",
    title: "Operation builder",
    structure: "Structure",
    underlying: "Underlying",
    underlyingPlaceholder: "e.g. PETR4",
    price: "Price",
    pricing: "Pricing…",
    priceError: "Could not price this operation with the current data.",
    noRiskProfileChip: "no risk profile",
    save: "Save operation",
    saved: "Operation saved.",
    saveError: "Could not save this operation.",
    legsTable: {
      title: "Legs",
      side: "Side",
      quantity: "Quantity",
      instrument: "Instrument",
      type: "Type",
      strike: "Strike",
      expiry: "Expiry",
      price: "Price",
      delta: "Delta",
      iv: "IV",
      buy: "Buy",
      sell: "Sell",
      call: "Call",
      put: "Put",
      stock: "Stock",
      pickInstrument: "Pick an instrument",
    },
    statBlocks: {
      title: "Result",
      netPremium: "Net premium",
      maxLoss: "Max loss",
      maxGain: "Max gain",
      breakEvens: "Break-evens",
      unbounded: "Unbounded",
    },
    greeksPanel: {
      title: "Greeks",
      delta: "Delta",
      gamma: "Gamma",
      theta: "Theta",
      vega: "Vega",
      thetaUnit: "/ session",
      vegaUnit: "/ point",
    },
    riskNotice: {
      title: "Limit breach",
      recordAnyway: "Record anyway",
      limits: {
        maxLossPerOperation: "Max loss per operation",
        maxExposurePerOperation: "Max exposure per operation",
        maxOpenOperations: "Max open operations",
        maxPremiumBought: "Max option premium bought",
      },
    },
    payoffChart: { underlying: "Underlying price", pnl: "P&L at expiry" },
  },
  list: {
    title: "Contemplated operations",
    newOperation: "New operation",
    empty: "No contemplated operations yet.",
    columns: {
      underlying: "Underlying",
      date: "Date",
      netPremium: "Net premium",
      maxLoss: "Max loss",
      breach: "Breach",
    },
  },
};

const ptBR = {
  builder: {
    overline: "Nova operação",
    title: "Montador de operações",
    structure: "Estrutura",
    underlying: "Ativo-objeto",
    underlyingPlaceholder: "ex.: PETR4",
    price: "Precificar",
    pricing: "Precificando…",
    priceError: "Não foi possível precificar esta operação com os dados atuais.",
    noRiskProfileChip: "sem perfil de risco",
    save: "Salvar operação",
    saved: "Operação salva.",
    saveError: "Não foi possível salvar esta operação.",
    legsTable: {
      title: "Pernas",
      side: "Lado",
      quantity: "Quantidade",
      instrument: "Instrumento",
      type: "Tipo",
      strike: "Strike",
      expiry: "Vencimento",
      price: "Preço",
      delta: "Delta",
      iv: "Vol. implícita",
      buy: "Compra",
      sell: "Venda",
      call: "Call",
      put: "Put",
      stock: "Ação",
      pickInstrument: "Escolha um instrumento",
    },
    statBlocks: {
      title: "Resultado",
      netPremium: "Prêmio líquido",
      maxLoss: "Perda máxima",
      maxGain: "Ganho máximo",
      breakEvens: "Pontos de equilíbrio",
      unbounded: "Ilimitado",
    },
    greeksPanel: {
      title: "Gregas",
      delta: "Delta",
      gamma: "Gama",
      theta: "Theta",
      vega: "Vega",
      thetaUnit: "/ sessão",
      vegaUnit: "/ ponto",
    },
    riskNotice: {
      title: "Limite excedido",
      recordAnyway: "Registrar mesmo assim",
      limits: {
        maxLossPerOperation: "Perda máxima por operação",
        maxExposurePerOperation: "Exposição máxima por operação",
        maxOpenOperations: "Máximo de operações abertas",
        maxPremiumBought: "Prêmio máximo comprado em opções",
      },
    },
    payoffChart: { underlying: "Preço do ativo-objeto", pnl: "Resultado no vencimento" },
  },
  list: {
    title: "Operações contempladas",
    newOperation: "Nova operação",
    empty: "Nenhuma operação contemplada ainda.",
    columns: {
      underlying: "Ativo-objeto",
      date: "Data",
      netPremium: "Prêmio líquido",
      maxLoss: "Perda máxima",
      breach: "Limite",
    },
  },
} satisfies typeof en;

export const operationsStrings = { en, ptBR } as const;

export const t = operationsStrings.ptBR;
