const en = {
  list: {
    overline: "Strategies",
    title: "Strategies",
    newStrategy: "New strategy",
    mine: {
      title: "My strategies",
      empty: "No strategy in your catalog yet. Create one from a structure.",
      columns: { name: "Name", visibility: "Visibility", version: "Version", updatedAt: "Updated" },
      edit: "Edit",
      share: "Share",
      unshare: "Stop sharing",
      shareError: "Couldn't update sharing. Try again.",
    },
    shared: {
      title: "Shared by other users",
      empty: "No strategy shared yet.",
      copy: "Copy",
      copyError: "Couldn't copy the strategy. Try again.",
    },
    visibility: { private: "Private", shared: "Shared" },
  },
  editor: {
    createOverline: "New strategy",
    editOverline: "Edit strategy",
    name: { label: "Name" },
    timeframe: { label: "Timeframe" },
    structure: { label: "Structure" },
    entry: {
      title: "Entry conditions",
      subtitle: "All conditions must hold (AND).",
      addCondition: "Add condition",
      removeCondition: "Remove condition",
      comparator: "Comparator",
      leftOperand: "First value",
      rightOperand: "Second value",
    },
    operand: {
      kind: "Type",
      indicatorKind: "Indicator",
      indicatorLength: "Length",
      indicatorLookback: "Lookback sessions",
      priceField: "Field",
      constantValue: "Value",
    },
    strikes: {
      title: "Strike selection",
      subtitle: "One row per strike, ranked in order.",
      addStrike: "Add strike",
      removeStrike: "Remove strike",
      kind: "Method",
      kinds: { delta: "Delta", moneyness: "Moneyness", nearest: "Nearest" },
      delta: { target: "Target delta" },
      moneyness: { percent: "Moneyness (%)" },
      nearest: { price: "Reference price" },
    },
    expiry: {
      title: "Expiry window",
      min: "Minimum business days",
      max: "Maximum business days",
    },
    sizing: {
      title: "Sizing",
      kind: "Method",
      fraction: "Fraction",
      fixed_fractional: "Fixed fractional",
      fixed_risk: "Fixed risk",
    },
    exit: {
      title: "Exit rules",
      addRule: "Add rule",
      removeRule: "Remove rule",
      kind: "Type",
      profit_target: "Profit target",
      stop_loss: "Stop loss",
      days_before_expiry: "Days before expiry",
      condition: "Condition",
      fractionOfPremium: "Fraction of the premium",
      multipleOfMaxLoss: "Multiple of the max loss",
      businessDays: "Business days",
    },
    adjustments: {
      title: "Adjustments",
      subtitle: "Optional rolls to a new expiry and strikes.",
      addAdjustment: "Add adjustment",
      removeAdjustment: "Remove adjustment",
      when: "Roll when",
    },
    submit: { create: "Create strategy", save: "Save new version" },
    cancel: "Cancel",
    invalid: "Some fields are invalid. Review the values before saving.",
    versions: { title: "Versions", createdAt: "Created" },
  },
  comparators: { ">": ">", ">=": "≥", "<": "<", "<=": "≤", "==": "=", "!=": "≠" },
  priceFields: {
    open: "Open",
    high: "High",
    low: "Low",
    close: "Close",
    tradedQuantity: "Traded quantity",
  },
  indicatorKinds: { sma: "SMA", ema: "EMA", rsi: "RSI", atr: "ATR", iv_rank: "IV rank" },
  operandKinds: { indicator: "Indicator", price: "Price field", constant: "Constant" },
};

const ptBR = {
  list: {
    overline: "Estratégias",
    title: "Estratégias",
    newStrategy: "Nova estratégia",
    mine: {
      title: "Minhas estratégias",
      empty:
        "Você ainda não tem nenhuma estratégia no catálogo. Crie uma a partir de uma estrutura.",
      columns: {
        name: "Nome",
        visibility: "Visibilidade",
        version: "Versão",
        updatedAt: "Atualizada em",
      },
      edit: "Editar",
      share: "Compartilhar",
      unshare: "Parar de compartilhar",
      shareError: "Não foi possível atualizar o compartilhamento. Tente novamente.",
    },
    shared: {
      title: "Compartilhadas por outros usuários",
      empty: "Nenhuma estratégia compartilhada ainda.",
      copy: "Copiar",
      copyError: "Não foi possível copiar a estratégia. Tente novamente.",
    },
    visibility: { private: "Privada", shared: "Compartilhada" },
  },
  editor: {
    createOverline: "Nova estratégia",
    editOverline: "Editar estratégia",
    name: { label: "Nome" },
    timeframe: { label: "Timeframe" },
    structure: { label: "Estrutura" },
    entry: {
      title: "Condições de entrada",
      subtitle: "Todas as condições precisam valer ao mesmo tempo (E).",
      addCondition: "Adicionar condição",
      removeCondition: "Remover condição",
      comparator: "Comparador",
      leftOperand: "Primeiro valor",
      rightOperand: "Segundo valor",
    },
    operand: {
      kind: "Tipo",
      indicatorKind: "Indicador",
      indicatorLength: "Período",
      indicatorLookback: "Sessões de referência",
      priceField: "Campo",
      constantValue: "Valor",
    },
    strikes: {
      title: "Seleção de strikes",
      subtitle: "Uma linha por strike, na ordem dos ranks.",
      addStrike: "Adicionar strike",
      removeStrike: "Remover strike",
      kind: "Método",
      kinds: { delta: "Delta", moneyness: "Moneyness", nearest: "Mais próximo" },
      delta: { target: "Delta alvo" },
      moneyness: { percent: "Moneyness (%)" },
      nearest: { price: "Preço de referência" },
    },
    expiry: {
      title: "Janela de vencimento",
      min: "Mínimo de sessões",
      max: "Máximo de sessões",
    },
    sizing: {
      title: "Dimensionamento",
      kind: "Método",
      fraction: "Fração",
      fixed_fractional: "Fração fixa",
      fixed_risk: "Risco fixo",
    },
    exit: {
      title: "Regras de saída",
      addRule: "Adicionar regra",
      removeRule: "Remover regra",
      kind: "Tipo",
      profit_target: "Alvo de lucro",
      stop_loss: "Stop",
      days_before_expiry: "Dias antes do vencimento",
      condition: "Condição",
      fractionOfPremium: "Fração do prêmio",
      multipleOfMaxLoss: "Múltiplo da perda máxima",
      businessDays: "Dias úteis",
    },
    adjustments: {
      title: "Ajustes",
      subtitle: "Rolagens opcionais para um novo vencimento e novos strikes.",
      addAdjustment: "Adicionar ajuste",
      removeAdjustment: "Remover ajuste",
      when: "Rolar quando",
    },
    submit: { create: "Criar estratégia", save: "Salvar nova versão" },
    cancel: "Cancelar",
    invalid: "Alguns campos estão inválidos. Revise os valores antes de salvar.",
    versions: { title: "Versões", createdAt: "Criada em" },
  },
  comparators: { ">": ">", ">=": "≥", "<": "<", "<=": "≤", "==": "=", "!=": "≠" },
  priceFields: {
    open: "Abertura",
    high: "Máxima",
    low: "Mínima",
    close: "Fechamento",
    tradedQuantity: "Quantidade negociada",
  },
  indicatorKinds: {
    sma: "Média móvel simples",
    ema: "Média móvel exponencial",
    rsi: "IFR",
    atr: "ATR",
    iv_rank: "Rank de IV",
  },
  operandKinds: { indicator: "Indicador", price: "Campo de preço", constant: "Constante" },
} satisfies typeof en;

export const strategiesStrings = { en, ptBR } as const;

export const t = strategiesStrings.ptBR;
